// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package reply

import (
	"fiber/internal/db"
	"fiber/internal/module/reply/controller"
	"fiber/internal/module/reply/repository"
	"fiber/internal/module/reply/service"
	"github.com/arangodb/go-driver"
)

// Injectors from wire.go:

// Wire injector
func InitializeReplyModule() *ReplyModule {
	database := db.ConnectArango()
	collection := provideReplyCollection(database)
	replyRepository := repository.NewReplyRepository(collection)
	replyService := service.NewReplyService(replyRepository)
	replyController := controller.NewReplyController(replyService)
	replyModule := NewReplyModule(database, replyController)
	return replyModule
}

// wire.go:

// Reply 컬렉션 Provider
func provideReplyCollection(d driver.Database) driver.Collection {
	return db.EnsureCollection(d, "replies")
}
