// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package board

import (
	"fiber/internal/db"
	"fiber/internal/module/board/controller"
	"fiber/internal/module/board/repository"
	"fiber/internal/module/board/service"
	"github.com/arangodb/go-driver"
)

// Injectors from wire.go:

// Wire injector
func InitializeBoardModule() *BoardModule {
	database := db.ConnectArango()
	collection := provideBoardCollection(database)
	boardRepository := repository.NewBoardRepository(collection)
	boardService := service.NewBoardService(boardRepository)
	boardController := controller.NewBoardController(boardService)
	boardModule := NewBoardModule(database, boardController)
	return boardModule
}

// wire.go:

// Board 컬렉션 Provider
func provideBoardCollection(d driver.Database) driver.Collection {
	return db.EnsureCollection(d, "boards")
}
