// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"fiber/internal/db"
	"fiber/internal/module/user/controller"
	"fiber/internal/module/user/repository"
	"fiber/internal/module/user/service"
	"github.com/arangodb/go-driver"
)

// Injectors from wire.go:

// Wire injector
func InitializeUserModule() *UserModule {
	database := db.ConnectArango()
	collection := provideUserCollection(database)
	userRepository := repository.NewUserRepository(collection)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	userModule := NewUserModule(database, userController)
	return userModule
}

// wire.go:

// User 컬렉션 Provider
func provideUserCollection(d driver.Database) driver.Collection {
	return db.EnsureCollection(d, "users")
}
